package com.ecommerce.observer;

import com.ecommerce.events.Event;
import com.ecommerce.order.Order;
import java.util.logging.Logger;

/**
 * Observer that logs all order events and status changes.
 * This code was generated by an LLM - hatchling
 */
public class LoggingOrderObserver implements OrderObserver {
    
    private static final Logger LOGGER = Logger.getLogger(LoggingOrderObserver.class.getName());
    
    @Override
    public void onOrderEvent(Order order, Event event) {
        LOGGER.info(String.format("Order Event: %s for Order %s (Customer: %s, Status: %s)", 
            event.getEventType(), order.getOrderId(), order.getCustomerId(), order.getStatus()));
    }
    
    @Override
    public void onOrderStatusChanged(Order order, String oldStatus, String newStatus) {
        LOGGER.info(String.format("Order Status Change: Order %s status changed from %s to %s", 
            order.getOrderId(), oldStatus, newStatus));
    }
}
